-- Run this SQL in Supabase Dashboard > SQL Editor.
create table if not exists public.players (
  name text primary key,
  reflex_score integer,
  aim_speed double precision,
  aim_hits integer not null default 0,
  aim_total_time integer not null default 0,
  aim_accuracy double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.country_visits (
  id bigint generated by default as identity primary key,
  player_name text not null,
  ip_address text not null,
  country_code text not null,
  country_name text not null,
  is_domestic boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.country_visits enable row level security;

create policy "public can read players" on public.players for select to anon using (true);
create policy "public can add players" on public.players for insert to anon with check (true);
create policy "public can update players" on public.players for update to anon using (true) with check (true);
create policy "public can read visits" on public.country_visits for select to anon using (true);
create policy "public can add visits" on public.country_visits for insert to anon with check (true);
